name: 'Check homework submission before grading'

on:
  workflow_dispatch:
  push:

jobs:
  check-homework:
    
    runs-on: ubuntu-latest
    
    steps:
      - name: Checkout Repository
        uses: actions/checkout@v4
      
      - name: Set up Python 3.10 environment
        uses: actions/setup-python@v5
        with:
          python-version: '3.10'
      
      - name: Install Dependencies
        run: |
          python -m pip install --upgrade pip
          pip install nbconvert==7.9 ipython biopython Pillow
      
      - name: Checkout Actions Repository
        uses: actions/checkout@v4
        with:
          repository: IB-ULFRI/homework-actions
          path: ./homework-actions

      - name: Check Syntax
        uses: ./homework-actions/action-notebook-syntax

      - name: Explicit variables
        uses: ./homework-actions/action-explicit-variables
        with:
          args: >
            highest_cumulative_sum
            faster_mapping
            non_viral_material
            non_viral_origin
            num_cells
            num_genes
            diff_expressed_genes
            why_diff_expressed_genes
            meaningful_diff_expression
            enriched_GO_term
            GO_term_comments
            tsne_clusters
        
      - name: Notebook and helper_functions files present
        uses: ./homework-actions/action-files-present

      - name: Helper_functions compiles
        uses: ./homework-actions/action-helper-compiles

      - name: Check Images visible
        uses: ./homework-actions/action-images-white
      
      - name: Check Images real SVG
        uses: ./homework-actions/action-real-SVG-images
      
      - name: Images as SVGs
        uses: ./homework-actions/action-stored-SVG
        with:
          args: >
            realistic_gene_dict.svg
            realistic_cell_dist.svg
            volcano.svg
            sc_analysis_pca.svg
            sc_analysis_clusters.svg
            sc_analysis_deg.svg
            